#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

echo "[webcli] pulling latest changes..."
# package-lock.json is regenerated by npm install on each machine (node-pty
# is a native module, so its platform-specific fields drift between npm
# versions/OSes) and often ends up with a local diff that blocks a
# fast-forward pull. It's a derived file, so discarding local edits to it is
# always safe before pulling — npm install below regenerates it anyway.
git checkout -- package-lock.json 2>/dev/null || true
git pull --ff-only

if git diff --name-only HEAD@{1} HEAD 2>/dev/null | grep -qE '^package(-lock)?\.json$'; then
  echo "[webcli] package.json changed, running npm install..."
  npm install
fi

echo "[webcli] update complete, restarting..."
exec ./restart.sh
