@echo off
setlocal enabledelayedexpansion
cd /d "%~dp0"

echo [webcli] pulling latest changes...
REM package-lock.json is regenerated by npm install on each machine (node-pty
REM is a native module, so platform-specific fields drift) and often has a
REM local diff that blocks a fast-forward pull. It's a derived file, so
REM discarding local edits to it is safe -- npm install below regenerates it.
git checkout -- package-lock.json >nul 2>&1
git pull --ff-only
if errorlevel 1 (
  echo [webcli] git pull failed - resolve manually.
  pause
  exit /b 1
)

git diff --name-only HEAD@{1} HEAD > "%TEMP%\webcli_update_diff.txt" 2>nul
findstr /C:"package.json" /C:"package-lock.json" "%TEMP%\webcli_update_diff.txt" >nul
if %errorlevel%==0 (
  echo [webcli] package.json changed, running npm install...
  call npm install
)
del "%TEMP%\webcli_update_diff.txt" >nul 2>&1

echo [webcli] update complete, restarting...
call restart.bat
