#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

echo "[webcli] pulling latest changes..."
# package-lock.json is regenerated by npm install on each machine (node-pty
# is a native module, so its platform-specific fields drift between npm
# versions/OSes) and often ends up with a local diff that blocks a
# fast-forward pull. It's a derived file, so discarding local edits to it is
# always safe before pulling — npm install below regenerates it anyway.
git checkout -- package-lock.json 2>/dev/null || true
git pull --ff-only

if git diff --name-only HEAD@{1} HEAD 2>/dev/null | grep -qE '^package(-lock)?\.json$'; then
  echo "[webcli] package.json changed, running npm install..."
  npm install
fi

PID_FILE="../data/webcli/server.pid"
if [ -f "$PID_FILE" ]; then
  OLD_PID="$(cat "$PID_FILE")"
  if kill -0 "$OLD_PID" 2>/dev/null; then
    echo "[webcli] stopping running instance (pid $OLD_PID)..."
    kill "$OLD_PID" 2>/dev/null || true
    for _ in $(seq 1 25); do
      kill -0 "$OLD_PID" 2>/dev/null || break
      sleep 0.2
    done
    kill -0 "$OLD_PID" 2>/dev/null && kill -9 "$OLD_PID" 2>/dev/null || true
  fi
fi

echo "[webcli] update complete, restarting..."
exec ./start.sh
